### ISSUE TITLE
Understanding FFX RNG

### ISSUE THREAD

**Issue by blakehartley** [Tranquilite0/FF12RNGHelperPC#1]
This isn't an issue with this program, but I didn't know how to reach you and this seemed like the method with the greatest chance of success. I am interested in understanding how the PRNG of FFX works, as I would like to find a method to manipulate a specific armor drop in the game. I already know that the PRNG that I am trying to manipulate is seeded based on the console time when the game is turned on, but I don't know how to reverse engineer the PRNG formula. Your work with FFXII is inspiring, and I was wondering if you could share anything about how you reverse engineered the MT PRNG: did you use cheat engine with an emulator, is the MT ubiquitous with PS2 games, etc. Thanks!

**Comment by Tranquilite0** [comment]
Much of the original reverse engineering was done long before I entered the scene. The original "cure list" was actually an excel spreadsheet out there that had the first 30,000 or so PRNG values along with some formulas for calculating cure values. Also most of what I learned came from [this](http://www.kotha.net/ff12random/random-en.html) site along with other various sources that I was able to google years ago. Most of the work I have done with TZA has just involved educated guesses and a bit of luck.

With that said for the PC version of TZA I did have to do some real reverse engineering. I did use cheat engine both for searching for the places in memory where the PRNG state changed, as well as for viewing the disassembly to try and trace the logic the game used to seed the PRNG.

As for your query about trying to manipulate enemy drops, the site I linked mentioned that there are at least 3 different PRNG sources that are independent of each other. While it has been a long time since I have tested things, I vaguely recall coming to the conclusion that enemy drops are not handled by the same PRNG that handles chest drops/damage/etc. I fear you may have a lot of work cut out for you. Good luck!

**Comment by bijohammax** [comment]
Hi Tranquilite0!

I have the RNG running with the new version but for some reason the Advance for Result number doesnt move anymore. It will only move when an action is performed like a spell being cast or combat. It used to move all the time. I have rebooted and exited the game quite a few times, changed zones, warped, new save file. I cannot figure out why the number does not move on its own anymore. It seems like the RNG doesn't generate if an action is not performed.

**Comment by Tranquilite0** [comment]
Hmm, I have a few ideas.

First off, make sure your "item 1 chance", "gil chance", and "desired result" options are set appropriately for the treasure you are trying to manipulate.

Also double check the environment where this is happening. Typically the RNG will advance either:
1) When you perform actions
2) When you move between zones which require random numbers to determine chest spawns, rare monster spawns, or weather changes
3) In zones where there is random NPC movement
4) Other miscellaneous things like the Regen status effect or the Gambits of Guest party members

Honestly, the behavior you are describing seems pretty normal to me. In most situations, I have to manually advance the RNG by casting cure or punching myself. Are you used to manipulating the RNG while wearing auto-regen equipment like Ribbons, or in crowded places like the Airship?

**Comment by bijohammax** [comment]
Thanks!

It was regen. That starts the down tick in the number. I guess I switched out my regen gambit user.

Thanks again!
